version: '3.8'

services:
  db:
    image: redis:alpine
    container_name: db

  app:
    image: app:latest
    container_name: app
    env_file: ./.env

    ports:
      - 3000:3000

    build:
      dockerfile: dockerfile.app

    depends_on:
      - db
