version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    env_file: .env
    ports:
      - 6379:6379

  app:
    image: app:latest
    container_name: app
    env_file: .env

    ports:
      - 3000:3000

    build:
      dockerfile: dockerfile.app

    depends_on:
      - redis
